sylius_twig_hooks:
    hooks:
        sylius_admin.constructor.update.content.header:
            breadcrumbs:
                template: '@SyliusAdmin/shared/crud/show/content/header/breadcrumbs.html.twig'
                configuration:
                    rendered_field: name
                priority: 0
