liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    filter_sets:
        app_game_image:
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: outbound }
